ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitignore ~/.gitignore
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/bashrc ~/.bashrc
ln -s ~/dotfiles/zshrc ~/.zshrc
ln -s ~/dotfiles/zshrc-private ~/.zshrc-private
ln -s ~/dotfiles/gemrc ~/.gemrc
ln -s ~/dotfiles/irbrc ~/.irbrc
ln -s ~/dotfiles/rspec ~/.rspec
